# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket                      = "terraform-states-134293017362"
    dynamodb_table              = "terraform-locks-134293017362"
    encrypt                     = true
    key                         = "aws-data/terraform.tfstate"
    region                      = "us-east-2"
    skip_credentials_validation = true
    skip_metadata_api_check     = true
  }
}
